FindHouseAndT.WebApp/Pages/CustomerPages/CommonView/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FindHouseAndT.WebApp.Pages.CustomerPages.CommonView
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

FindHouseAndT.WebApp/Pages/CustomerPages/CommonView/Index.cshtml.cs
using FindHouseAndT.Application.Services;
using FindHouseAndT.Application.DTOs;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FindHouseAndT.WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IMotelService _motelService;
        public List<MotelManagerDTO> ListMotels { get; set; } = new List<MotelManagerDTO>();

        public IndexModel(IMotelService motelService) {
            _motelService = motelService;
        }

        public async Task OnGet()
        {
            ListMotels = await _motelService.GetAllMotelAsync();
        }
        public void OnPost(Guid idMotel)
        {
            var motel = _motelService.GetMotelById(idMotel);
            if (motel != null)
            {
                ViewData["motel"] = motel;
            }
        }
    }
}

FindHouseAndT.WebApp/Pages/CustomerPages/CommonView/MotelDetail.cshtml.cs
using FindHouseAndT.Application.Services;
using FindHouseAndT.Application.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FindHouseAndT.Application.ExternalInterface;

namespace FindHouseAndT.WebApp.Pages.CustomerPages.CommonView
{
    public class MotelDetailModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public Guid MotelId { get; set; }
        public MotelManagerDTO Motel { get; set; } = null!;
        public List<RoomManagerDTO> Rooms { get; set; } = new List<RoomManagerDTO>();
        private readonly IMotelService _motelService;
        private readonly IFileStorageService _amazonService;

        public MotelDetailModel(IMotelService motelService, IFileStorageService amazonService)
        {
            _motelService = motelService;
            _amazonService = amazonService;
        }

        public async void OnGet()
        {
            if(!MotelId.Equals(Guid.Empty))
            {
                var motel = _motelService.GetMotelById(MotelId);
                if(motel != null)
                {
                    Motel = new MotelManagerDTO()
                    {
                        Address = motel.Address,
                        Description1 = motel.Description1,
                        Description2 = motel.Description2,
                        IdMotel = motel.IdMotel,
                        QuantityRoom = motel.QuantityRoom,
                        Name = motel.Name,
                        ImageMotel = await _amazonService.GetPreSignedUrlAsync(motel.KeyImageMotel)
                    };
                    foreach (var room in motel.Rooms)
                    {
                        Rooms.Add(new RoomManagerDTO()
                        {
                            Area = room.Area,
                            Description1 = room.Description1,
                            Description2= room.Description2,
                            Floor = room.Floor,
                            IdMotel = room.IdMotel,
                            Price = room.Price,
                            Status = room.Status,
                            RoomCode = room.RoomCode,
                            UrlImageRoom = await _amazonService.GetPreSignedUrlAsync(room.KeyImageRoom)
                        });
                    }
                }
                
            }
        }
    }
}

FindHouseAndT.WebApp/Pages/CustomerPages/CommonView/UserManager.cshtml.cs
using FindHouseAndT.Application.Services;
using FindHouseAndT.Models.Entities;
using FindHouseAndT.Models.Helper;
using FindHouseAndT.Models.MailKit;
using FindHouseAndT.Application.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FindHouseAndT.Application.ExternalInterface;

namespace FindHouseAndT.WebApp.Pages.CustomerPages
{
	public class UserManagerModel : PageModel
	{
		[BindProperty]
		public RegisterDTO RegisterDTO { get; set; } = new RegisterDTO();
		[BindProperty]
		public LoginDTO LoginDTO { get; set; } = new LoginDTO();
		private readonly UserManager<UserApp> _userManager;
		private readonly ICustomerService _customerService;
		private readonly IEmailService _mailService;
		private readonly SignInManager<UserApp> _signInManager;
		public UserManagerModel(UserManager<UserApp> userManager, ICustomerService customerService, IEmailService mailService, SignInManager<UserApp> signInManager)
		{
			_userManager = userManager;
			_customerService = customerService;
			_mailService = mailService;
			_signInManager = signInManager;
		}

		public async Task OnGetAsync()
		{
			LoginDTO.Schemes = await _signInManager.GetExternalAuthenticationSchemesAsync();
		}

		public async Task<IActionResult> OnPostRegisterAsync()
		{
			ModelState.Clear();

			if (TryValidateModel(RegisterDTO, nameof(RegisterDTO)))
			{
				var result1 = await _userManager.FindByEmailAsync(RegisterDTO.Email);
				if (result1 != null)
				{
					ModelState.AddModelError("Email", "Email is exist.");
				}
				else
				{
					var user = new UserApp()
					{
						UserName = RegisterDTO.Email,
						Email = RegisterDTO.Email,
						EmailConfirmed = false
					};
					var custom = new Customer()
					{
						Name = RegisterDTO.FullName,
						BirthDate = RegisterDTO.BirthDate,
					};
					var result2 = await _userManager.CreateAsync(user, RegisterDTO.Password);
					if (result2.Succeeded)
					{
						var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
						var callbackUrl = Url.Page(
                            "/CustomerPages/CustomerView/ConfirmEmail",
							pageHandler: null,
							values: new { userId = user.Id, code = code },
							protocol: Request.Scheme);
						var mailContent = new MailContent() { Email = user.Email, Content = $"Please confirm your account by <a href='{callbackUrl}'>clicking here</a>.", Subject = "Welcome" };
						var result = await _mailService.SendMailAsync(mailContent);
						await _userManager.AddToRoleAsync(user, UserRole.Customer);
						custom.IdUser = user.Id;
						var result3 = await _customerService.Register(custom);
						if (result3.ResultCode == ResultCode.Success)
						{
							return Redirect("/CustomerPages/CommonView/Index");
						}
					}
				}
			}
			return Page();

		}

		public async Task<IActionResult> OnPostLoginAsync()
		{
			ModelState.Clear();

			if (TryValidateModel(LoginDTO, nameof(LoginDTO)))
			{
				var user = await _userManager.FindByEmailAsync(LoginDTO.Email);
                if (user == null)
                {
					ModelState.AddModelError("Not found", "Not found User");
					return NotFound("Not found user.");
				}
				else
				{
					if (!await _userManager.CheckPasswordAsync(user, LoginDTO.Password))
					{
						ModelState.AddModelError("Error", "Error Password");
					}
					else
					{
						if(!await _userManager.IsEmailConfirmedAsync(user))
						{
							return RedirectToPage("/CustomerPages/CustomerView/ConfirmEmail");
						}
						await _signInManager.SignInAsync(user, isPersistent: false);
						return RedirectToPage("/CustomerPages/CommonView/Index");
					}
				}
				
            }
			LoginDTO.Schemes = await _signInManager.GetExternalAuthenticationSchemesAsync();
			return Page();
		}
		[BindProperty]
		public string Provider {  get; set; } = string.Empty;
		public IActionResult OnPostExternalLogin()
		{
			if(Provider == null)
			{
				return Page();
			}
			var redirect = Url.Page("/CustomerPages/CustomerView/ExternalLoginCallBack");
			var property = _signInManager.ConfigureExternalAuthenticationProperties(Provider, redirect);
			return new ChallengeResult(Provider, property);
		}
		public async Task<IActionResult> OnGetSignOutAsync()
		{
			LoginDTO.Schemes = await _signInManager.GetExternalAuthenticationSchemesAsync();
			await _signInManager.SignOutAsync();
			return RedirectToPage("/CustomerPages/CommonView/UserManager");
		}
	}
}

FindHouseAndT.WebApp/Pages/CustomerPages/CustomerView/BookRequestManager.cshtml.cs
using FindHouseAndT.Application.Services;
using FindHouseAndT.Models.Helper;
using FindHouseAndT.Application.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using FindHouseAndT.Models.Entities;
using FindHouseAndT.Application.ExternalInterface;

namespace FindHouseAndT.WebApp.Pages.CustomerPages.CustomerView
{
	[Authorize(Roles = UserRole.Customer)]
	public class BookRequestManagerModel : PageModel
	{
		[BindProperty(SupportsGet = true)]
		public string RoomCode { get; set; } = string.Empty;
		[BindProperty(SupportsGet = true)]
		public Guid IdMotel { get; set; } = new Guid();
		private readonly IRoomService roomService;
		private readonly IFileStorageService amazonService;
		private readonly ICustomerService customerService;
		private readonly IBookRequestService bookRequestService;
		private readonly UserManager<UserApp> userManager;

		public BookRequestManagerModel(IRoomService roomService, UserManager<UserApp> userManager, IFileStorageService amazonService, ICustomerService customerService, IBookRequestService bookRequestService)
		{
			this.roomService = roomService;
			this.amazonService = amazonService;
			this.customerService = customerService;
			this.bookRequestService = bookRequestService;
			this.userManager = userManager;
		}
		[BindProperty]
		public BookRequestCreateDTO BookRequestDTO { get; set; } = new BookRequestCreateDTO();

		public async Task<IActionResult> OnGetAsync()
		{
			var userIdClaim = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
			if (!string.IsNullOrEmpty(RoomCode) && userIdClaim != null)
			{
				BookRequestDTO = await bookRequestService.GetInforBookRequestCreateDTOAsync(Guid.Parse(userIdClaim.Value), RoomCode, IdMotel);
				return Page();
			}
			else
			{
				return RedirectToPage("/CustomerPages/CommonView/AccessDenied");
			}
		}

		public async Task<IActionResult> OnPostAsync()
		{
			var userIdClaim = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier);
			if (userIdClaim != null && ModelState.IsValid)
			{
				BookRequestDTO.IdCustomer = Guid.Parse(userIdClaim.Value);
                var result = await bookRequestService.CreateNewBookRequestAsync(BookRequestDTO);
                if (result.ResultCode == ResultCode.Success)
                {
                    return RedirectToPage("/CustomerPages/CustomerView/ListBookRequest");
                }
			}
			return RedirectToPage("/CustomerPages/CommonView/AccessDenied");
		}
	}
}

FindHouseAndT.WebApp/Pages/CustomerPages/CustomerView/ConfirmEmail.cshtml.cs
using FindHouseAndT.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FindHouseAndT.WebApp.Pages.CustomerPages
{
	public class ConfirmEmailModel : PageModel
	{
		private UserManager<UserApp> _userManager;

		public ConfirmEmailModel(UserManager<UserApp> userManager)
		{
			_userManager = userManager;
		}

		public bool IsEmailConfirmed { get; set; }
		public async Task<IActionResult> OnGetAsync(string userId, string code)
		{
			if (userId != null && code != null)
			{
				var user = await _userManager.FindByIdAsync(userId);
				if (user == null)
				{
					return NotFound($"Not found User {userId}");
				}
				var result = await _userManager.ConfirmEmailAsync(user, code);
				if (result.Succeeded)
				{
					IsEmailConfirmed = true;
				}
			}
			return Page();
		}
	}
}

FindHouseAndT.WebApp/Pages/CustomerPages/CustomerView/ExternalLoginCallBack.cshtml.cs
using FindHouseAndT.Application.Services;
using FindHouseAndT.Models.Entities;
using FindHouseAndT.Models.Helper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace FindHouseAndT.WebApp.Pages.CustomerPages
{
	public class ExternalLoginCallBackModel : PageModel
	{
		private readonly SignInManager<UserApp> _signInManager;
		private readonly UserManager<UserApp> _userManager;
		private readonly ICustomerService _customerService;

		public ExternalLoginCallBackModel(SignInManager<UserApp> signInManager, UserManager<UserApp> userManager, ICustomerService customerService)
		{
			_signInManager = signInManager;
			_userManager = userManager;
			_customerService = customerService;
		}

		public async Task<IActionResult> OnGetAsync(string returnUrl, string remoteError)
		{
			var infor = await _signInManager.GetExternalLoginInfoAsync();
			if (infor == null)
			{
				return RedirectToPage("/CustomerPages/CommonView/UserManager");
			}
			var signInResult = await _signInManager.ExternalLoginSignInAsync(infor.LoginProvider, infor.ProviderKey, isPersistent: false);
			if (signInResult.Succeeded)
			{
				return RedirectToPage("/CustomerPages/CommonView/Index");
			}
			else
			{
				var email = infor.Principal.FindFirstValue(ClaimTypes.Email);
				if (email == null)
				{
					return RedirectToPage("/CustomerPages/CommonView/UserManager");
				}
				var getUser = await _userManager.FindByEmailAsync(email);
				if (getUser != null)
				{
					await _userManager.AddLoginAsync(getUser, infor);
					await _signInManager.SignInAsync(getUser, isPersistent: false);
					return RedirectToPage("/CustomerPages/CommonView/Index");
				}
				var user = new UserApp()
				{
					UserName = email,
					Email = email,
					EmailConfirmed = true
				};
				var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
					var addLoginResult = await _userManager.AddLoginAsync(user, infor);
					var customer = new Customer() {IdUser = user.Id, Name = user.Email };
					var addCustomerResult = await _customerService.Register(customer);
					var addToRoleResult = await _userManager.AddToRoleAsync(user, UserRole.Customer);
					if (addLoginResult.Succeeded && addCustomerResult.ResultCode == ResultCode.Success && addToRoleResult.Succeeded)
					{
						await _signInManager.SignInAsync(user, isPersistent: false);
						return RedirectToPage("/CustomerPages/CommonView/Index");
					}
                }
				return RedirectToPage("/CustomerPages/CommonView/UserManager");
			}
		}
	}
}

FindHouseAndT.WebApp/Pages/CustomerPages/CustomerView/ListBookRequest.cshtml.cs
using FindHouseAndT.Application.DTOs;
using FindHouseAndT.Application.Services;
using FindHouseAndT.Models.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace FindHouseAndT.WebApp.Pages.CustomerPages.CustomerView
{
    [Authorize(Roles = UserRole.Customer)]
    public class ListBookRequestModel : PageModel
    {
        private readonly IBookRequestService bookRequestService;

        public ListBookRequestModel(IBookRequestService bookRequestService)
        {
            this.bookRequestService = bookRequestService;
        }

        public List<BookRequestShowListDTO> Books { get; set; } = new List<BookRequestShowListDTO>();
        public async Task<IActionResult> OnGet()
        {
            var claimUserId = User.FindFirst(x => x.Type == ClaimTypes.NameIdentifier);
            if(claimUserId == null)
            {
                return RedirectToPage("");
            }
            Books = await bookRequestService.GetAllBookRequestByCustomerIdAsync(Guid.Parse(claimUserId.Value));
            return Page();
        }
        [BindProperty(SupportsGet = true)]
        public int BookRequestId { get; set; }
        public async Task<IActionResult> OnGetLoadBookRequest()
        {
            if (BookRequestId != 0)
            {
                var list = await bookRequestService.GetAllBookRequestForShowListAsync();
                var br = list.Where(x => x.Id == BookRequestId).SingleOrDefault();
                return new JsonResult(br);
            }
            return new JsonResult("Error");
        }
    }
}

FindHouseAndT.WebApp/Pages/CustomerPages/CustomerView/ProfileUser.cshtml.cs
using FindHouseAndT.Application.Services;
using FindHouseAndT.Models.Entities;
using FindHouseAndT.Application.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using FindHouseAndT.Models.Helper;
using System.Security.Claims;

namespace FindHouseAndT.WebApp.Pages.CustomerPages
{
    [Authorize(Roles = UserRole.Customer)]
    public class ProfileUserModel : PageModel
    {
        private readonly ICustomerService _customerService;
        [BindProperty]
        public ProfileCustomerDTO ProfileUserDTO { get; set; } = new ProfileCustomerDTO();

        public ProfileUserModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public async Task<IActionResult> OnGet()
        {
            var userIdClaims = User.FindFirst(ClaimTypes.NameIdentifier);
            if (userIdClaims == null)
            {
                return RedirectToPage("/CustomerPages/CommonView/AccessDenied");
            }
            ProfileUserDTO = await _customerService.GetProfileCustomerAsync(Guid.Parse(userIdClaims.Value));
            return Page();
        }
        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid)
            {
                await _customerService.UpdateCustomer(ProfileUserDTO);
			}
			return Page();
        }
    }
}

FindHouseAndT.WebApp/Pages/CustomerPages/CommonView/AccessDenied.cshtml
@page
@model FindHouseAndT.WebApp.Pages.CustomerPages.CommonView.AccessDeniedModel
@{
}
<div class="alert-danger">Access Denied</div>

FindHouseAndT.WebApp/Pages/CustomerPages/CommonView/UserManager.cshtml
@page
@model FindHouseAndT.WebApp.Pages.CustomerPages.UserManagerModel
@{
}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-12 col-md-4">
			<!-- Pills navs -->
			<ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
				<li class="nav-item" role="presentation">
					<a class="nav-link active" id="tab-login" data-toggle="pill" href="#pills-login" role="tab"
					   aria-controls="pills-login" aria-selected="true">Login</a>
				</li>
				<li class="nav-item" role="presentation">
					<a class="nav-link" id="tab-register" data-toggle="pill" href="#pills-register" role="tab"
					   aria-controls="pills-register" aria-selected="false">Register</a>
				</li>
			</ul>
			<!-- Pills navs -->
			<!-- Pills content -->
			<div class="tab-content">
				<div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
					<div class="text-center mb-3">
						<p>Sign in with:</p>
						<form asp-page-handler="ExternalLogin" method="post">
						@if (Model.LoginDTO.Schemes.Count() > 0)
						{
							@foreach (var provider in Model.LoginDTO.Schemes)
							{
								<button  type="submit" name="Provider" value="@provider.Name" title="Login using abc @provider.Name Account" class="btn btn-link mx-1">
									<span class="ms-2 fs-6">@provider.DisplayName</span>
								</button>
							}
						}
						</form>
					</div>
					<form asp-page-handler="Login" method="post">
						

						<p class="text-center">or:</p>
						<div asp-validation-summary="All" class="text-danger"></div>
						<!-- Email input -->
						<div class="form-group mb-4">
							<label asp-for="LoginDTO.Email" class="form-label"></label>
							<input asp-for="LoginDTO.Email" class="form-control" />
							<span asp-validation-for="LoginDTO.Email" class="text-danger"></span>
						</div>

						<!-- Password input -->
						<div class="form-group mb-4">
							<label asp-for="LoginDTO.Password" class="form-label"></label>
							<input asp-for="LoginDTO.Password" class="form-control" />
							<span asp-validation-for="LoginDTO.Password" class="text-danger"></span>
						</div>

						<!-- 2 column grid layout -->
						<div class="row mb-4">
							<div class="col-md-6 d-flex justify-content-center">
								<!-- Checkbox -->
								<div class="form-check mb-3 mb-md-0">
									<input class="form-check-input" type="checkbox" value="" id="loginCheck" checked />
									<label class="form-check-label" for="loginCheck"> Remember me </label>
								</div>
							</div>

							<div class="col-md-6 d-flex justify-content-center">
								<!-- Simple link -->
								<a href="#!">Forgot password?</a>
							</div>
						</div>

						<!-- Submit button -->
						<button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

						<!-- Register buttons -->
						<div class="text-center">
							<p>Not a member? <a href="#!">Register</a></p>
						</div>
					</form>
				</div>
				<div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="tab-register">
					<form asp-page-handler="Register" method="post">
						<div asp-validation-summary="All" class="text-danger"></div>
						<div class="text-center mb-3">
							<p>Sign up with:</p>
							<button type="button" class="btn btn-link mx-1">
								<i class="fab fa-facebook-f"></i>
							</button>

							<button type="button" class="btn btn-link mx-1">
								<i class="fab fa-google"></i>
							</button>

							<button type="button" class="btn btn-link mx-1">
								<i class="fab fa-twitter"></i>
							</button>

							<button type="button" class="btn btn-link mx-1">
								<i class="fab fa-github"></i>
							</button>
						</div>

						<p class="text-center">or:</p>

						<!-- Name input -->
						<div class="form-group mb-4">
							<label asp-for="RegisterDTO.FullName" class="form-label"></label>
							<input asp-for="RegisterDTO.FullName" class="form-control" />
							<span asp-validation-for="RegisterDTO.FullName" class="text-danger"></span>
						</div>

						<!-- Username input -->
						<div class="form-group mb-4">
							<label asp-for="RegisterDTO.Email" class="form-label"></label>
							<input asp-for="RegisterDTO.Email" class="form-control" />
							<span asp-validation-for="RegisterDTO.Email" class="text-danger"></span>
						</div>

						<!-- Email input -->
						<div class="form-group mb-4">
							<label class="form-label" asp-for="RegisterDTO.BirthDate"></label>
							<input asp-for="RegisterDTO.BirthDate" class="form-control" />
							<span asp-validation-for="RegisterDTO.BirthDate" class="text-danger"></span>
						</div>

						<!-- Password input -->
						<div class="form-group mb-4">
							<label class="form-label" asp-for="RegisterDTO.Password"></label>
							<input asp-for="RegisterDTO.Password" class="form-control" />
							<span asp-validation-for="RegisterDTO.Password" class="text-danger"></span>
						</div>

						<!-- Repeat Password input -->
						<div class="form-group mb-4">
							<label class="form-label" asp-for="RegisterDTO.ConfirmPassword"></label>
							<input asp-for="RegisterDTO.ConfirmPassword" class=" form-control" />
							<span asp-validation-for="RegisterDTO.ConfirmPassword" class="text-danger"></span>
						</div>

						<!-- Checkbox -->
						@* <div class="form-check d-flex justify-content-center mb-4">
							<input class="form-check-input me-2" type="checkbox" value="" id="registerCheck" checked
								   aria-describedby="registerCheckHelpText" />
							<label class="form-check-label" for="registerCheck">
								I have read and agree to the terms
							</label>
						</div> *@

						<!-- Submit button -->
						<button type="submit" class="btn btn-primary btn-block mb-3">Sign up</button>
					</form>
				</div>
			</div>
			<!-- Pills content -->
		</div>
	</div>
</div>