FindHouseAndT.WebApp/Pages/CustomerPages/CommonView/UserManager.cshtml.cs
using FindHouseAndT.Application.Services;
using FindHouseAndT.Models.Entities;
using FindHouseAndT.Models.Helper;
using FindHouseAndT.Models.MailKit;
using FindHouseAndT.Application.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FindHouseAndT.Application.ExternalInterface;

namespace FindHouseAndT.WebApp.Pages.CustomerPages
{
	public class UserManagerModel : PageModel
	{
		[BindProperty]
		public RegisterDTO RegisterDTO { get; set; } = new RegisterDTO();
		[BindProperty]
		public LoginDTO LoginDTO { get; set; } = new LoginDTO();
		private readonly UserManager<UserApp> _userManager;
		private readonly ICustomerService _customerService;
		private readonly IEmailService _mailService;
		private readonly SignInManager<UserApp> _signInManager;
		public UserManagerModel(UserManager<UserApp> userManager, ICustomerService customerService, IEmailService mailService, SignInManager<UserApp> signInManager)
		{
			_userManager = userManager;
			_customerService = customerService;
			_mailService = mailService;
			_signInManager = signInManager;
		}

		public async Task OnGetAsync()
		{
			LoginDTO.Schemes = await _signInManager.GetExternalAuthenticationSchemesAsync();
		}

		public async Task<IActionResult> OnPostRegisterAsync()
		{
			ModelState.Clear();

			if (TryValidateModel(RegisterDTO, nameof(RegisterDTO)))
			{
				var result1 = await _userManager.FindByEmailAsync(RegisterDTO.Email);
				if (result1 != null)
				{
					ModelState.AddModelError("Email", "Email is exist.");
				}
				else
				{
					var user = new UserApp()
					{
						UserName = RegisterDTO.Email,
						Email = RegisterDTO.Email,
						EmailConfirmed = false
					};
					var custom = new Customer()
					{
						Name = RegisterDTO.FullName,
						BirthDate = RegisterDTO.BirthDate,
					};
					var result2 = await _userManager.CreateAsync(user, RegisterDTO.Password);
					if (result2.Succeeded)
					{
						var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
						var callbackUrl = Url.Page(
                            "/CustomerPages/CustomerView/ConfirmEmail",
							pageHandler: null,
							values: new { userId = user.Id, code = code },
							protocol: Request.Scheme);
						var mailContent = new MailContent() { Email = user.Email, Content = $"Please confirm your account by <a href='{callbackUrl}'>clicking here</a>.", Subject = "Welcome" };
						var result = await _mailService.SendMailAsync(mailContent);
						await _userManager.AddToRoleAsync(user, UserRole.Customer);
						custom.IdUser = user.Id;
						var result3 = await _customerService.Register(custom);
						if (result3.ResultCode == ResultCode.Success)
						{
							return Redirect("/CustomerPages/CommonView/Index");
						}
					}
				}
			}
			return Page();

		}

		public async Task<IActionResult> OnPostLoginAsync()
		{
			ModelState.Clear();

			if (TryValidateModel(LoginDTO, nameof(LoginDTO)))
			{
				var user = await _userManager.FindByEmailAsync(LoginDTO.Email);
                if (user == null)
                {
					ModelState.AddModelError("Not found", "Not found User");
					return NotFound("Not found user.");
				}
				else
				{
					if (!await _userManager.CheckPasswordAsync(user, LoginDTO.Password))
					{
						ModelState.AddModelError("Error", "Error Password");
					}
					else
					{
						if(!await _userManager.IsEmailConfirmedAsync(user))
						{
							return RedirectToPage("/CustomerPages/CustomerView/ConfirmEmail");
						}
						await _signInManager.SignInAsync(user, isPersistent: false);
						return RedirectToPage("/CustomerPages/CommonView/Index");
					}
				}
				
            }
			LoginDTO.Schemes = await _signInManager.GetExternalAuthenticationSchemesAsync();
			return Page();
		}
		[BindProperty]
		public string Provider {  get; set; } = string.Empty;
		public IActionResult OnPostExternalLogin()
		{
			if(Provider == null)
			{
				return Page();
			}
			var redirect = Url.Page("/CustomerPages/CustomerView/ExternalLoginCallBack");
			var property = _signInManager.ConfigureExternalAuthenticationProperties(Provider, redirect);
			return new ChallengeResult(Provider, property);
		}
		public async Task<IActionResult> OnGetSignOutAsync()
		{
			LoginDTO.Schemes = await _signInManager.GetExternalAuthenticationSchemesAsync();
			await _signInManager.SignOutAsync();
			return RedirectToPage("/CustomerPages/CommonView/UserManager");
		}
	}
}

FindHouseAndT.WebApp/Pages/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<Models.Entities.UserApp> signInManager
@using FindHouseAndT.Models.Helper
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - FindHouseAndT.WebApp</title>


	<!-- <link rel="manifest" href="site.webmanifest"> -->
	<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
	<!-- Place favicon.ico in the root directory -->
	<!-- CSS here -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/css/owl.carousel.min.css">
	<link rel="stylesheet" href="~/css/magnific-popup.css">
	<link rel="stylesheet" href="~/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/css/themify-icons.css">
	<link rel="stylesheet" href="~/css/nice-select.css">
	<link rel="stylesheet" href="~/css/flaticon.css">
	<link rel="stylesheet" href="~/css/gijgo.css">
	<link rel="stylesheet" href="~/css/animate.css">
	<link rel="stylesheet" href="~/css/slicknav.css">
	<link rel="stylesheet" href="~/css/style.css">
	@RenderSection("StyleSection", required: false)
</head>
<body>
	<!-- header-start -->
	<header>
		<div class="header-area ">
			<div id="sticky-header" class="main-header-area">
				<div class="container-fluid p-0">
					<div class="row align-items-center no-gutters">
						<div class="col-xl-5 col-lg-6">
							<div class="main-menu  d-none d-lg-block">
								<nav>
									<ul id="navigation">
										<li><a class="active" asp-page="/CustomerPages/CommonView/Index">home</a></li>
										<li><a href="rooms.html">rooms</a></li>
										<li><a href="about.html">About</a></li>
										<li>
											<a href="#">blog <i class="ti-angle-down"></i></a>
											<ul class="submenu">
												<li><a href="blog.html">blog</a></li>
												<li><a href="single-blog.html">single-blog</a></li>
											</ul>
										</li>
										<li>
											<a href="#">pages <i class="ti-angle-down"></i></a>
											<ul class="submenu">
												<li><a href="elements.html">elements</a></li>
											</ul>
										</li>
										<li>
											@if (signInManager.IsSignedIn(User))
											{
												if (User.IsInRole(UserRole.Customer))
												{
													<a asp-page="/CustomerPages/CustomerView/ListBookRequest">Book Requests</a>
												}
											}
										</li>
									</ul>
								</nav>
							</div>
						</div>
						<div class="col-xl-2 col-lg-2">
							<div class="logo-img">
								<a href="index.html">
									<img src="img/logo.png" alt="">
								</a>
							</div>
						</div>
						<div class="col-xl-5 col-lg-4 d-none d-lg-block">
							<div class="book_room">
								<div class="socail_links">
									<ul>
										<li>
											<a href="#">
												<i class="fa fa-facebook-square"></i>
											</a>
										</li>
										<li>
											<a href="#">
												<i class="fa fa-twitter"></i>
											</a>
										</li>
										<li>
											<a href="#">
												<i class="fa fa-instagram"></i>
											</a>
										</li>
									</ul>
								</div>
								@if (signInManager.IsSignedIn(User))
								{
									if (User.IsInRole(UserRole.Landlord))
									{
										<div class="book_btn d-none d-lg-block">
											<a asp-page="/ManagerPages/HomeManager">Manager Motel</a>
										</div>
										<div class="book_btn d-none d-lg-block">
											<a asp-page="/CustomerPages/CommonView/UserManager" asp-page-handler="SignOut">Sign Out</a>
										</div>
									}
									else
									{
										<div class="book_btn d-none d-lg-block">
											<a asp-page="/CustomerPages/CustomerView/ProfileUser">User</a>
										</div>
										<div class="book_btn d-none d-lg-block">
											<a asp-page="/CustomerPages/CommonView/UserManager" asp-page-handler="SignOut">Sign Out</a>
										</div>
									}
								}
								else
								{
									<div class="book_btn d-none d-lg-block">
										<a asp-page="/CustomerPages/CommonView/UserManager">Login/Register</a>
									</div>
								}

							</div>
						</div>
						<div class="col-12">
							<div class="mobile_menu d-block d-lg-none"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<div class="slider_area">
		<div class="slider_active owl-carousel">
			<div class="single_slider d-flex align-items-center justify-content-center slider_bg_1">
				<div class="container">
					<div class="row">
						<div class="col-xl-12">
							<div class="slider_text text-center">
								<h3>Montana Resort</h3>
								<p>Unlock to enjoy the view of Martine</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="single_slider  d-flex align-items-center justify-content-center slider_bg_2">
				<div class="container">
					<div class="row">
						<div class="col-xl-12">
							<div class="slider_text text-center">
								<h3>Life is Beautiful</h3>
								<p>Unlock to enjoy the view of Martine</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="single_slider d-flex align-items-center justify-content-center slider_bg_1">
				<div class="container">
					<div class="row">
						<div class="col-xl-12">
							<div class="slider_text text-center">
								<h3>Montana Resort</h3>
								<p>Unlock to enjoy the view of Martine</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="single_slider  d-flex align-items-center justify-content-center slider_bg_2">
				<div class="container">
					<div class="row">
						<div class="col-xl-12">
							<div class="slider_text text-center">
								<h3>Life is Beautiful</h3>
								<p>Unlock to enjoy the view of Martine</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- header-end -->
	@* <div class="container">
	<main role="main" class="pb-3">
	@RenderBody()
	</main>
	</div> *@
	@RenderBody()
	<footer class="footer">
		<div class="footer_top">
			<div class="container">
				<div class="row">
					<div class="col-xl-3 col-md-6 col-lg-3">
						<div class="footer_widget">
							<h3 class="footer_title">
								address
							</h3>
							<p class="footer_text">
								200, Green road, Mongla, <br>
								New Yor City USA
							</p>
							<a href="#" class="line-button">Get Direction</a>
						</div>
					</div>
					<div class="col-xl-3 col-md-6 col-lg-3">
						<div class="footer_widget">
							<h3 class="footer_title">
								Reservation
							</h3>
							<p class="footer_text">
								+10 367 267 2678 <br>
								reservation@montana.com
							</p>
						</div>
					</div>
					<div class="col-xl-2 col-md-6 col-lg-2">
						<div class="footer_widget">
							<h3 class="footer_title">
								Navigation
							</h3>
							<ul>
								<li><a href="#">Home</a></li>
								<li><a href="#">Rooms</a></li>
								<li><a href="#">About</a></li>
								<li><a href="#">News</a></li>
							</ul>
						</div>
					</div>
					<div class="col-xl-4 col-md-6 col-lg-4">
						<div class="footer_widget">
							<h3 class="footer_title">
								Newsletter
							</h3>
							<form action="#" class="newsletter_form">
								<input type="text" placeholder="Enter your mail">
								<button type="submit">Sign Up</button>
							</form>
							<p class="newsletter_text">Subscribe newsletter to get updates</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="copy-right_text">
			<div class="container">
				<div class="footer_border"></div>
				<div class="row">
					<div class="col-xl-8 col-md-7 col-lg-9">
						<p class="copy_right">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</div>
					<div class="col-xl-4 col-md-5 col-lg-3">
						<div class="socail_links">
							<ul>
								<li>
									<a href="#">
										<i class="fa fa-facebook-square"></i>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-twitter"></i>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-instagram"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	@RenderSection("ScriptSection", required: false);
	<!-- JS here -->
	<script src="~/js/vendor/modernizr-3.5.0.min.js"></script>
	<script src="~/js/vendor/jquery-1.12.4.min.js"></script>
	<script src="~/js/popper.min.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	<script src="~/js/owl.carousel.min.js"></script>
	<script src="~/js/isotope.pkgd.min.js"></script>
	<script src="~/js/ajax-form.js"></script>
	<script src="~/js/waypoints.min.js"></script>
	<script src="~/js/jquery.counterup.min.js"></script>
	<script src="~/js/imagesloaded.pkgd.min.js"></script>
	<script src="~/js/scrollIt.js"></script>
	<script src="~/js/jquery.scrollUp.min.js"></script>
	<script src="~/js/wow.min.js"></script>
	<script src="~/js/nice-select.min.js"></script>
	<script src="~/js/jquery.slicknav.min.js"></script>
	<script src="~/js/jquery.magnific-popup.min.js"></script>
	<script src="~/js/plugins.js"></script>
	<script src="~/js/gijgo.min.js"></script>

	<!--contact js-->
	<script src="~/js/contact.js"></script>
	<script src="~/js/jquery.ajaxchimp.min.js"></script>
	<script src="~/js/jquery.form.js"></script>
	<script src="~/js/jquery.validate.min.js"></script>
	<script src="~/js/mail-script.js"></script>

	<script src="~/js/main.js"></script>

	
</body>
</html>

FindHouseAndT.WebApp/Pages/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home-Manager</title>
    <link rel="shortcut icon" type="image/png" href="~/assets/images/logos/favicon.png" />
    <link rel="stylesheet" href="~/assets/css/styles.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/gijgo.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/slicknav.css">
    <link rel="stylesheet" href="~/css/style.css">
    @RenderSection("StyleSection", required: false);
</head>
<body>
    
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <!-- Sidebar Start -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div>
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a asp-page="/CustomerPages/CommonView/Index" class="text-nowrap logo-img">
                        <img src="../assets/images/logos/dark-logo.svg" width="180" alt="" />
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                    <ul id="sidebarnav">
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Home</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-page="/ManagerPages/HomeManager" aria-expanded="false">
                                <span>
                                    <i class="ti ti-layout-dashboard"></i>
                                </span>
                                <span class="hide-menu">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">UI COMPONENTS</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-page="/ManagerPages/MotelManager" aria-expanded="false">
                                <span>
                                    <i class="ti ti-article"></i>
                                </span>
                                <span class="hide-menu">Motel Manager</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-page="/ManagerPages/RoomManager" aria-expanded="false">
                                <span>
                                    <i class="ti ti-alert-circle"></i>
                                </span>
                                <span class="hide-menu">Room Manager</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-page="/ManagerPages/ListBookRequestManager" aria-expanded="false">
                                <span>
                                    <i class="ti ti-cards"></i>
                                </span>
                                <span class="hide-menu">Book Request Manager</span>
                            </a>
                        </li>
                        
                    </ul>
                    <div class="unlimited-access hide-menu bg-light-primary position-relative mb-7 mt-5 rounded">
                        <div class="d-flex">
                            <div class="unlimited-access-title me-3">
                                <h6 class="fw-semibold fs-4 mb-6 text-dark w-85">Upgrade to pro</h6>
                                <a href="https://adminmart.com/product/modernize-bootstrap-5-admin-template/" target="_blank" class="btn btn-primary fs-2 fw-semibold lh-sm">Buy Pro</a>
                            </div>
                            <div class="unlimited-access-img">
                                <img src="../assets/images/backgrounds/rocket.png" alt="" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!--  Sidebar End -->
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <!--  Header Start -->
            <header class="app-header">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <ul class="navbar-nav">
                        <li class="nav-item d-block d-xl-none">
                            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                                <i class="ti ti-menu-2"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                                <i class="ti ti-bell-ringing"></i>
                                <div class="notification bg-primary rounded-circle"></div>
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    <img src="../assets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                    <div class="message-body">
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-user fs-6"></i>
                                            <p class="mb-0 fs-3">My Profile</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-mail fs-6"></i>
                                            <p class="mb-0 fs-3">My Account</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-list-check fs-6"></i>
                                            <p class="mb-0 fs-3">My Task</p>
                                        </a>
                                        <a href="./authentication-login.html" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!--  Header End -->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    @RenderSection("ScriptSection", required: false);
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/sidebarmenu.js"></script>
    <script src="~/assets/js/app.min.js"></script>
    <script src="~/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/assets/libs/simplebar/dist/simplebar.js"></script>
    <script src="~/assets/js/dashboard.js"></script>
    <script src="~/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/isotope.pkgd.min.js"></script>
    <script src="~/js/ajax-form.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/js/scrollIt.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/nice-select.min.js"></script>
    <script src="~/js/jquery.slicknav.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/gijgo.min.js"></script>
</body>
</html>